#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | yang689 独立维护版 | 选点页面请使用自部署 Worker
#!author=yang689
#!homepage=https://github.com/yang689/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/yang689/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/yang689/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
